# Use root/example as user/password credentials
version: '3.8'

services:
  postgres:
    container_name: what_app
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"

     #docker compose -p tmsky-nodejs-mysql up -d